user nginx;
worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    gzip on;
    gzip_types text/plain application/json application/javascript text/css application/xml;
    include /etc/nginx/conf.d/*.conf;
}
